# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 操作系统实验2016
description: > # this means to ignore newlines until "baseurl:"
    Powered by Jekyll with default theme
baseurl: "/oslab" # the subpath of your site, e.g. /blog
url: "http://www.wonicon.com" # the base hostname & protocol for your site

# Build settings
# Use redcarpet instead of the default kramdown
# to support fency code block
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
permalink: /:title.html
